name: Build

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java 11
      uses: actions/setup-java@v1
      with:
        java-version: 11

    - name: Set up Java 8
      uses: actions/setup-java@v1
      with:
        java-version: 8

    - name: Cache gradle dependencies
      uses: actions/cache@v1
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Goodness knows what I'm doing
      run: env

    - name: Build with Gradle
      run: ./gradlew build --no-daemon || ./gradlew build --no-daemon

    - name: Upload Jar
      uses: actions/upload-artifact@v1
      with:
        name: CC-Tweaked
        path: build/libs

    - name: Upload Coverage
      run: bash <(curl -s https://codecov.io/bash)

  lint-lua:
    name: Lint Lua
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Lint Lua code
      run: |
        test -d bin || mkdir bin
        test -f bin/illuaminate || wget -q -Obin/illuaminate https://squiddev.cc/illuaminate/linux-x86-64/illuaminate
        chmod +x bin/illuaminate
        bin/illuaminate lint

    - name: Check whitespace
      run: python3 tools/check-lines.py
